name: New CI with Allure History

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Restore Allure History
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || exit 0
          cp -R gh-pages/history target/allure-results/history || echo "No previous history"

      - name: Run tests
        run: mvn clean test

      - name: Download Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz

      - name: Generate Allure Report
        run: |
          ./allure-2.27.0/bin/allure generate target/allure-results --clean -o allure-report
          cp -R target/allure-results/history allure-report/history || echo "No history to copy"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages